language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: "15e3147bf4be5a636802935ce9c8f7b24f90956e"

jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
